[build]
  base = "upsc-gurukul-frontend"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  LIGHTNING_CSS_USE_WASM = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
